export var config = {
	//technique
  port: 8089,
  server: "localhost",
  protocol: "http",
  // labels
  boutontraitementpalynologie: "Lancer analyse palyno",
  boutontraitementresidus: "Lancer analyse résidu",
  boutontraitementaggregationresidus: "Télécharger pdf résidus aggrégés",
  exportercsv: "Exporter CSV",
  traitementencours: "Traitement en cours ...",
  tempsestime: "Temps estimé",
  dateestime: "Heure de fin estimée",
  enregistrer: "Valider",
  nom: "Nom",
  pourcentage: "Pourcentage",
  dominant: "Dominant",
  accompagnement: "Accompagnement",
  isole: "Isolé",
  echantillon: "Echantillon",
  reference: "Référence",
  gms: "GMS - GC-MSMS - Primoris accredited",
  lms: "LMS - LC-MSMS - Primoris accredited",
  t2mult: "2",
  t1mult: "8",
  titre: "Infos abeilles extracteur !",
  ajouterligne: "Ajouter une ligne",
  trace: "Trace",
  poids: "Poids",
  certificatAnalyse: "Certificat d'analyses",
  appelation: "Appelation demandeur",
  boutontraitementcsvresidus: "Télécharger CSV résidus",
  boutontraitementcsvpalyno: "Télécharger CSV palynologie"
}